<?xml version="1.0"?>
<package format="3">
  <name>thunder_ahand</name>
  <version>0.0.0</version>
  <description>Allegro Hand V5 implementation via thunder dynamics library.</description>

  <!-- One maintainer tag required, multiple allowed, one person per tag -->
  <maintainer email="leonardo.marcello_99@hotmail.com">Leonardo Marcello</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Add dependencies -->
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
